apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:  
      hostname: busybox-1
      containers:
        - name: redis
          image: redis
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "300m"
          imagePullPolicy: Always
          volumeMounts:
            - name: redis-volume
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 10
            initialDelaySeconds: 20
            periodSeconds: 3
            timeoutSeconds: 20
      volumes: 
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  clusterIP: 10.105.0.1
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379

    

