apiVersion: v1
kind: Service
metadata:
  name: fe-result-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      targetPort: 80
      port: 7002
  selector:
    app: fe-result
    type: frontend