apiVersion: v1
kind: Service
metadata:
  name: fe-vote-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      targetPort: 80
      port: 7001
  selector:
    app: fe-vote
    type: frontend